# Generated by Django 5.2.5 on 2025-08-27 16:48

import django.contrib.auth.models
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(default='', max_length=100)),
                ('city', models.CharField(default='', max_length=100)),
                ('state', models.CharField(default='', max_length=100)),
                ('street', models.CharField(default='', max_length=100)),
                ('location', models.CharField(default='', max_length=250)),
                ('longitude', models.CharField(blank=True, default='', max_length=100)),
                ('latitude', models.CharField(blank=True, default='', max_length=100)),
            ],
            options={
                'verbose_name_plural': 'Address',
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kycDocType', models.CharField(choices=[('PASSPORT', 'Passeport'), ('CNI', 'Carte d Identité')], default='CNI', max_length=20)),
                ('profileLink', models.CharField(blank=True, default='a.png', max_length=255)),
                ('facebookLink', models.CharField(blank=True, default='', max_length=255)),
                ('instagramLink', models.CharField(blank=True, default='', max_length=255)),
                ('rectoLink', models.CharField(blank=True, default='a.png', max_length=255)),
                ('versoLink', models.CharField(blank=True, default='a.png', max_length=255)),
                ('selfieLink', models.CharField(blank=True, default='a.png', max_length=255)),
                ('passportLink', models.CharField(blank=True, default='a.png', max_length=255)),
                ('gender', models.CharField(blank=True, choices=[('M', 'Masculin'), ('F', 'Feminin'), ('I', 'Inconnue')], default='I', max_length=25)),
            ],
            options={
                'verbose_name_plural': 'Profiles',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('identity', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('username', models.CharField(default='', max_length=50)),
                ('phone', models.CharField(blank=True, default='', max_length=50)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('VALID_KYC', 'Valider Kcy'), ('ENABLE', 'Active'), ('DISABLE', 'Disable'), ('REJECT_KYC', 'Rejeter Kyc'), ('PENDING', 'En cours'), ('PENDING_KYC', 'Demande Kcy'), ('CANCELLED', 'Supprimé')], default='ENABLE', max_length=50)),
                ('segment', models.CharField(blank=True, choices=[('etudiant', 'Étudiant'), ('professionnel', 'Professionnel'), ('entreprise', 'Entreprise'), ('institution', 'Institution publique')], max_length=20)),
                ('is_email_verify', models.BooleanField(default=False)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
                ('address', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_address', to='users.address')),
                ('profile', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_profile', to='users.profile')),
            ],
            options={
                'verbose_name_plural': 'Users',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='AuthSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.TextField(default='')),
                ('refresh', models.TextField(default='')),
                ('login_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('logout_at', models.DateTimeField(auto_now=True)),
                ('app', models.CharField(choices=[('WEB', 'Web'), ('TPE', 'Terminal de paiement'), ('MOBILE', 'Mobile'), ('DESKTOP', 'Ordinateur fixe')], default='WEB', max_length=50)),
                ('status', models.CharField(choices=[('OPEN', 'Ouverte'), ('CLOSE', 'Fermée')], default='OPEN', max_length=50)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Sessions',
            },
        ),
        migrations.CreateModel(
            name='Functionality',
            fields=[
                ('code', models.CharField(choices=[('DASHBOARD', 'Dashboard'), ('CUSTOMERS', 'Compte Clients'), ('ENTITIES', 'Entités'), ('USERS', 'Utilisateurs'), ('STOCKS', 'Stocks'), ('SALES', 'Ventes'), ('PURCHASES', 'Achats'), ('MARKETING', 'Communications'), ('SETTINGS', 'Parametrages')], max_length=50, primary_key=True, serialize=False)),
                ('libelle', models.CharField(default='', max_length=80)),
                ('icon', models.CharField(default='', max_length=80)),
                ('url', models.CharField(default='', max_length=80)),
                ('status', models.CharField(choices=[('ENABLE', 'Active'), ('DISABLE', 'Desactive'), ('ARCHIVE', 'Archivé'), ('CANCEL', 'Supprimé')], default='ENABLE', max_length=50)),
                ('orderby', models.IntegerField(default=1)),
                ('parent', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='functionalityParent', to='users.functionality')),
                ('roles', models.ManyToManyField(blank=True, related_name='fonctionnalites', to='auth.group')),
            ],
            options={
                'verbose_name_plural': 'Functionalities',
            },
        ),
        migrations.CreateModel(
            name='PartnerInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ninea', models.CharField(blank=True, default='', max_length=40)),
                ('phone', models.CharField(blank=True, default='', max_length=20)),
                ('email', models.EmailField(blank=True, default='', max_length=254)),
                ('logo', models.URLField(blank=True, default='')),
                ('logoTicket', models.URLField(blank=True, default='')),
                ('website', models.URLField(blank=True, default='')),
                ('first_color', models.CharField(blank=True, default='', max_length=20)),
                ('second_color', models.CharField(blank=True, default='', max_length=20)),
                ('third_color', models.CharField(blank=True, default='', max_length=20)),
                ('address', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='entity_address', to='users.address')),
            ],
            options={
                'verbose_name_plural': 'PartnerInfos',
            },
        ),
        migrations.CreateModel(
            name='Entity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identity', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('ENABLE', 'Active'), ('DISABLE', 'Desactive'), ('ARCHIVE', 'Archivé'), ('CANCEL', 'Supprimé')], default='ENABLE', max_length=50)),
                ('title', models.CharField(max_length=80)),
                ('subtitle', models.CharField(default='', max_length=100)),
                ('entitytype', models.CharField(choices=[('RACINE', 'Racine'), ('FOURNISSEUR', 'Fournisseur'), ('BOUTIQUE', 'Boutique'), ('CAISSE', 'Caisse'), ('UNIVERSITY', 'Université'), ('SCHOOL', 'École'), ('CORPORATE', 'Entreprise'), ('INSTITUTION', 'Institution publique')], max_length=80)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL)),
                ('parent', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='entityParent', to='users.entity')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL)),
                ('infos', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='entities', to='users.partnerinfo')),
            ],
            options={
                'verbose_name_plural': 'Entities',
            },
        ),
    ]
