# Generated by Django 5.2.5 on 2025-09-08 16:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='entity',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users_entity', to='users.entity'),
        ),
        migrations.AlterField(
            model_name='user',
            name='address',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users_address', to='users.address'),
        ),
        migrations.AlterField(
            model_name='user',
            name='profile',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users_profile', to='users.profile'),
        ),
        migrations.AlterField(
            model_name='user',
            name='status',
            field=models.CharField(choices=[('CANCELLED', 'Supprimé'), ('ENABLE', 'Active'), ('VALID_KYC', 'Valider Kcy'), ('PENDING_KYC', 'Demande Kcy'), ('DISABLE', 'Disable'), ('REJECT_KYC', 'Rejeter Kyc'), ('PENDING', 'En cours')], default='ENABLE', max_length=50),
        ),
    ]
