# Generated by Django 5.2.5 on 2025-09-11 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_entity_alter_user_address_alter_user_profile_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='entity',
            options={'verbose_name_plural': 'Entitées'},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'Utilisateur', 'verbose_name_plural': 'Utilisateurs'},
        ),
        migrations.AlterField(
            model_name='user',
            name='status',
            field=models.CharField(choices=[('PENDING_KYC', 'Demande Kcy'), ('REJECT_KYC', 'Rejeter Kyc'), ('ENABLE', 'Active'), ('CANCELLED', 'Supprimé'), ('DISABLE', 'Disable'), ('VALID_KYC', 'Valider Kcy'), ('PENDING', 'En cours')], default='ENABLE', max_length=50),
        ),
    ]
