# Generated by Django 5.2.5 on 2025-10-23 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_entity_options_alter_user_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='status',
            field=models.CharField(choices=[('DISABLE', 'Disable'), ('ENABLE', 'Active'), ('VALID_KYC', 'Valider Kcy'), ('CANCELLED', 'Supprimé'), ('REJECT_KYC', 'Rejeter Kyc'), ('PENDING', 'En cours'), ('PENDING_KYC', 'Demande Kcy')], default='ENABLE', max_length=50),
        ),
    ]
