# Generated by Django 5.2.5 on 2025-10-23 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_user_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='status',
            field=models.CharField(choices=[('DISABLE', 'Disable'), ('PENDING', 'En cours'), ('PENDING_KYC', 'Demande Kcy'), ('ENABLE', 'Active'), ('VALID_KYC', 'Valider Kcy'), ('REJECT_KYC', 'Rejeter Kyc'), ('CANCELLED', 'Supprimé')], default='ENABLE', max_length=50),
        ),
    ]
