# Generated by Django 5.2.5 on 2025-10-23 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_user_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='status',
            field=models.CharField(choices=[('PENDING_KYC', 'Demande Kcy'), ('ENABLE', 'Active'), ('DISABLE', 'Disable'), ('PENDING', 'En cours'), ('CANCELLED', 'Supprimé'), ('VALID_KYC', 'Valider Kcy'), ('REJECT_KYC', 'Rejeter Kyc')], default='ENABLE', max_length=50),
        ),
    ]
