# Generated by Django 5.2.5 on 2025-10-23 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_alter_user_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='status',
            field=models.CharField(choices=[('PENDING', 'En cours'), ('CANCELLED', 'Supprimé'), ('PENDING_KYC', 'Demande Kcy'), ('REJECT_KYC', 'Rejeter Kyc'), ('ENABLE', 'Active'), ('VALID_KYC', 'Valider Kcy'), ('DISABLE', 'Disable')], default='ENABLE', max_length=50),
        ),
    ]
