# Generated by Django 5.2.5 on 2025-10-23 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_alter_user_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='status',
            field=models.CharField(choices=[('ENABLE', 'Active'), ('DISABLE', 'Disable'), ('REJECT_KYC', 'Rejeter Kyc'), ('CANCELLED', 'Supprimé'), ('PENDING_KYC', 'Demande Kcy'), ('VALID_KYC', 'Valider Kcy'), ('PENDING', 'En cours')], default='ENABLE', max_length=50),
        ),
    ]
