# Generated by Django 5.2.5 on 2025-09-03 20:03

import django.core.validators
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_key', models.CharField(blank=True, max_length=40)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Panier',
                'verbose_name_plural': 'Paniers',
            },
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identity', models.CharField(default='<function ', editable=False, unique=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('ENABLE', 'Active'), ('DISABLE', 'Desactive'), ('ARCHIVE', 'Archivé'), ('CANCEL', 'Supprimé')], default='ENABLE', max_length=50)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('invoiceStatus', models.CharField(choices=[('PENDING', 'En cours'), ('UNPAID', 'Non payée'), ('PAID', 'Payé'), ('ORDER', 'Commande'), ('PROFORMA', 'Proforma'), ('RECEIVED', 'Livrée'), ('COMPETED', 'Completée'), ('ARCHIVE', 'Archivée'), ('CANCEL', 'Supprimée')], default='UNPAID', max_length=50)),
                ('paymentStatus', models.CharField(choices=[('UNPAID', 'Non payé'), ('PAID', 'Payé'), ('PARTIAL', 'Partiel'), ('DUE', 'Restant'), ('ARCHIVE', 'Archivé'), ('CANCEL', 'Supprimé')], default='UNPAID', max_length=50)),
                ('payed_at', models.DateTimeField(blank=True, null=True)),
                ('printCounter', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name_plural': 'Invoices',
            },
        ),
        migrations.CreateModel(
            name='ItemCart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)])),
                ('created_date', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Item cart',
                'verbose_name_plural': 'Items cart',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identity', models.CharField(default='<function ', editable=False, unique=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('ENABLE', 'Active'), ('DISABLE', 'Desactive'), ('ARCHIVE', 'Archivé'), ('CANCEL', 'Supprimé')], default='ENABLE', max_length=50)),
                ('source', models.CharField(choices=[('ECOM', 'E-commerce'), ('POS', 'Point de Vente')], max_length=4)),
                ('phoneNumber', models.CharField(blank=True, db_column='telephone', max_length=80)),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('discount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('delivery_fees', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('note', models.TextField(blank=True, default='')),
                ('order_status', models.CharField(choices=[('pending', 'En attente'), ('confirmed', 'Confirmée'), ('processing', 'En traitement'), ('shipped', 'Expédiée'), ('delivered', 'Livrée'), ('cancelled', 'Annulée'), ('refunded', 'Remboursée')], default='pending', max_length=20)),
            ],
            options={
                'verbose_name_plural': 'commands',
                'db_table': 'command',
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('code', models.CharField(choices=[('orange_money', 'Orange Money'), ('wave', 'Wave'), ('carte_credit', 'Carte de crédit'), ('virement', 'Virement bancaire'), ('especes', 'Paiement en espèces')], max_length=100)),
                ('icon', models.CharField(default='', max_length=250)),
                ('status', models.CharField(choices=[('ENABLE', 'Active'), ('DISABLE', 'Desactive'), ('ARCHIVE', 'Archivé'), ('CANCEL', 'Supprimé')], default='ENABLE', max_length=50)),
            ],
            options={
                'verbose_name_plural': 'payments',
            },
        ),
        migrations.CreateModel(
            name='QRCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(default='', max_length=55, verbose_name='Contenu du QR Code')),
                ('url', models.TextField(default='', verbose_name='image_urls')),
                ('image', models.ImageField(null=True, upload_to='qrcodes/')),
            ],
        ),
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identity', models.CharField(default='<function ', editable=False, unique=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('ENABLE', 'Active'), ('DISABLE', 'Desactive'), ('ARCHIVE', 'Archivé'), ('CANCEL', 'Supprimé')], default='ENABLE', max_length=50)),
                ('quantity', models.IntegerField(default=0)),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
            ],
            options={
                'verbose_name_plural': 'sales',
                'db_table': 'sale',
            },
        ),
    ]
