# Generated by Django 5.2.5 on 2025-09-03 17:24

import django.core.validators
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Avis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identity', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('ENABLE', 'Active'), ('DISABLE', 'Desactive'), ('ARCHIVE', 'Archivé'), ('CANCEL', 'Supprimé')], default='ENABLE', max_length=50)),
                ('note', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)])),
                ('comment', models.TextField(default='')),
                ('is_approve', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Avis',
                'verbose_name_plural': 'Avis',
            },
        ),
        migrations.CreateModel(
            name='Brands',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identity', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('ENABLE', 'Active'), ('DISABLE', 'Desactive'), ('ARCHIVE', 'Archivé'), ('CANCEL', 'Supprimé')], default='ENABLE', max_length=50)),
                ('name', models.CharField(max_length=80)),
                ('logo', models.FileField(upload_to='media/brands/')),
                ('slug', models.SlugField(blank=True, unique=True)),
            ],
            options={
                'verbose_name': 'Brand',
                'verbose_name_plural': 'Brands',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identity', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('ENABLE', 'Active'), ('DISABLE', 'Desactive'), ('ARCHIVE', 'Archivé'), ('CANCEL', 'Supprimé')], default='ENABLE', max_length=50)),
                ('name', models.CharField(max_length=80)),
                ('categoryType', models.CharField(choices=[('CATEGORY', 'Categorie'), ('SUBCATEGORY', 'Sous Categorie')], default='CATEGORY', max_length=80)),
                ('logo', models.FileField(upload_to='media/categories/')),
                ('slug', models.SlugField(blank=True, unique=True)),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identity', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('ENABLE', 'Active'), ('DISABLE', 'Desactive'), ('ARCHIVE', 'Archivé'), ('CANCEL', 'Supprimé')], default='ENABLE', max_length=50)),
                ('name', models.CharField(max_length=150)),
                ('description', models.TextField(default='')),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('qrcode', models.TextField(default='')),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('salePrice', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('minStock', models.IntegerField(default=0)),
                ('initialStock', models.IntegerField(default=0)),
                ('inStock', models.IntegerField(default=0)),
                ('outStock', models.IntegerField(default=0)),
                ('alert_threshold', models.IntegerField(default=10)),
                ('expiration_date', models.DateField(null=True)),
                ('entrepot_address', models.CharField(default='', max_length=20)),
                ('disponibility', models.CharField(choices=[('en_stock', 'En stock'), ('rupture', 'Rupture de stock'), ('precommande', 'Précommande')], default='en_stock', max_length=20)),
                ('badges', models.JSONField(blank=True, default=list)),
                ('specifications', models.JSONField(default=dict)),
                ('images', models.JSONField(default=list)),
                ('meta_title', models.CharField(blank=True, max_length=100)),
                ('meta_description', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Product',
                'verbose_name_plural': 'Products',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('url', models.TextField(default='', max_length=300)),
            ],
            options={
                'verbose_name_plural': 'Image products',
            },
        ),
        migrations.CreateModel(
            name='Promotion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identity', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('ENABLE', 'Active'), ('DISABLE', 'Desactive'), ('ARCHIVE', 'Archivé'), ('CANCEL', 'Supprimé')], default='ENABLE', max_length=50)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('type_promotion', models.CharField(choices=[('pourcentage', 'Pourcentage'), ('montant_fixe', 'Montant fixe'), ('livraison_gratuite', 'Livraison gratuite')], max_length=20)),
                ('value', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('date_debut', models.DateTimeField(auto_now=True)),
                ('date_fin', models.DateTimeField()),
                ('is_enable', models.BooleanField(default=True)),
                ('segments_cibles', models.JSONField(blank=True, default=list)),
            ],
            options={
                'ordering': ['-date_debut'],
            },
        ),
        migrations.CreateModel(
            name='StockMov',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identity', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('ENABLE', 'Active'), ('DISABLE', 'Desactive'), ('ARCHIVE', 'Archivé'), ('CANCEL', 'Supprimé')], default='ENABLE', max_length=50)),
                ('action', models.CharField(choices=[('in', 'Entrée'), ('out', 'Sortie'), ('adjust', 'Ajustement'), ('sold', 'Vente'), ('return', 'Retour')], max_length=20)),
                ('quantity', models.IntegerField()),
                ('previous_quantity', models.IntegerField()),
                ('new_quantity', models.IntegerField()),
                ('reason', models.TextField(blank=True)),
                ('reference', models.CharField(blank=True, max_length=100)),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Unity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identity', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('ENABLE', 'Active'), ('DISABLE', 'Desactive'), ('ARCHIVE', 'Archivé'), ('CANCEL', 'Supprimé')], default='ENABLE', max_length=50)),
                ('name', models.CharField(max_length=80)),
                ('code', models.CharField(default='<function uuid4 at 0x000002F920F49B20>', max_length=100, unique=True)),
                ('slug', models.CharField(default='', max_length=50)),
            ],
            options={
                'verbose_name_plural': 'Unities',
            },
        ),
    ]
