# Generated by Django 5.2.5 on 2025-09-08 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unity',
            name='code',
            field=models.CharField(default='<function uuid4 at 0x000001D3C1954A40>', max_length=100, unique=True),
        ),
    ]
