# Generated by Django 5.2.5 on 2025-09-11 23:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0003_alter_unity_code'),
        ('users', '0003_alter_entity_options_alter_user_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='unity',
            options={'verbose_name_plural': 'Unitées'},
        ),
        migrations.RemoveField(
            model_name='brands',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='brands',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='brands',
            name='deleted_at',
        ),
        migrations.RemoveField(
            model_name='brands',
            name='identity',
        ),
        migrations.RemoveField(
            model_name='brands',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='brands',
            name='updated_by',
        ),
        migrations.RemoveField(
            model_name='category',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='category',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='category',
            name='deleted_at',
        ),
        migrations.RemoveField(
            model_name='category',
            name='identity',
        ),
        migrations.RemoveField(
            model_name='category',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='category',
            name='updated_by',
        ),
        migrations.RemoveField(
            model_name='unity',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='unity',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='unity',
            name='deleted_at',
        ),
        migrations.RemoveField(
            model_name='unity',
            name='identity',
        ),
        migrations.RemoveField(
            model_name='unity',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='unity',
            name='updated_by',
        ),
        migrations.AddField(
            model_name='unity',
            name='store',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='unities_store', to='users.entity'),
        ),
        migrations.AlterField(
            model_name='unity',
            name='code',
            field=models.CharField(default='<function uuid4 at 0x000002BF74288A40>', max_length=100, unique=True),
        ),
    ]
