# Generated by Django 5.2.5 on 2025-10-23 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0004_alter_unity_options_remove_brands_created_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='badges',
        ),
        migrations.RemoveField(
            model_name='product',
            name='specifications',
        ),
        migrations.AddField(
            model_name='category',
            name='icon',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='category',
            name='logo',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='product',
            name='alert_threshold',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='disponibility',
            field=models.CharField(blank=True, choices=[('en_stock', 'En stock'), ('rupture', 'Rupture de stock'), ('precommande', 'Précommande')], default='en_stock', max_length=20),
        ),
        migrations.AlterField(
            model_name='product',
            name='entrepot_address',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='product',
            name='inStock',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='initialStock',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='minStock',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='outStock',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='salePrice',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='unity',
            name='code',
            field=models.CharField(default='<function uuid4 at 0x000001907FF54A40>', max_length=100, unique=True),
        ),
    ]
