# Generated by Django 5.2.5 on 2025-10-23 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0005_remove_product_badges_remove_product_specifications_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='images',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
        migrations.AlterField(
            model_name='unity',
            name='code',
            field=models.CharField(default='<function uuid4 at 0x000001B766AD4A40>', max_length=100, unique=True),
        ),
    ]
