# Generated by Django 5.2.5 on 2025-10-23 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0006_alter_product_images_alter_unity_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='meta_description',
        ),
        migrations.AlterField(
            model_name='product',
            name='meta_title',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='unity',
            name='code',
            field=models.CharField(default='<function uuid4 at 0x000002563D1A4A40>', max_length=100, unique=True),
        ),
    ]
