# Generated by Django 5.2.5 on 2025-10-23 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0007_remove_product_meta_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_promo',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='promo_percent',
            field=models.IntegerField(db_default=5, default=False, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='promo_price',
            field=models.IntegerField(db_default=5, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='unity',
            name='code',
            field=models.CharField(default='<function uuid4 at 0x0000028C3E724A40>', max_length=100, unique=True),
        ),
    ]
