# Generated by Django 5.2.5 on 2025-10-23 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0008_product_is_promo_product_promo_percent_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='promo_price',
        ),
        migrations.AlterField(
            model_name='unity',
            name='code',
            field=models.CharField(default='<function uuid4 at 0x0000028DA9304A40>', max_length=100, unique=True),
        ),
    ]
