# Generated by Django 5.2.5 on 2025-10-23 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0009_remove_product_promo_price_alter_unity_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unity',
            name='code',
            field=models.CharField(default='<function uuid4 at 0x000002D748788A40>', max_length=100, unique=True),
        ),
    ]
